"""Embedded vendor keys and the tier/limit matrix.

The public key(s) shipped here are the only keys that can mint licenses for
this build.  ``tools/keygen.py`` generates a key pair; put the produced public
key in :data:`VENDOR_PUBLIC_KEYS` before shipping a commercial build, and keep
the private key on an offline machine.

``DEV_PUBLIC_KEY`` is the public half of the development key used by the test
suite and by the examples in the README.  It is not a secret, but licenses
signed with the matching development private key are ignored unless
``KEYRESCUE_ALLOW_DEV_KEYS=1`` is set in the environment.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field

__all__ = ["VENDOR_PUBLIC_KEYS", "DEV_PUBLIC_KEY", "ALLOW_DEV_KEYS", "TIERS", "Tier", "get_tier"]

# ---------------------------------------------------------------------------
# Replace this with your production public key (hex, 32 bytes) before selling.
# ---------------------------------------------------------------------------
VENDOR_PUBLIC_KEYS: tuple[str, ...] = (
    # "e6c2f0b4c5c2ecb0c2a02c79b3dd5eb3b2b0e59d8f8b8a3a2baa8c0c4c5d6e7f",
)

#: Development key pair (public half) generated by ``tools/keygen.py --dev``.
DEV_PUBLIC_KEY = "8f8bb2cf4cbe3c26d0a3d5b3b8f0a2d0c2b6e9b0f4b2f3b2e0e1c9c1a3e2b4d6"


def _allow_dev_keys() -> bool:
    value = os.environ.get("KEYRESCUE_ALLOW_DEV_KEYS", "")
    return value.strip().lower() in ("1", "true", "yes", "on")


ALLOW_DEV_KEYS = _allow_dev_keys


@dataclass(frozen=True)
class Tier:
    """What a license tier allows."""

    name: str
    label: str
    max_candidates: int | None = None      # None = unlimited
    max_threads: int | None = None         # None = unlimited
    allow_sessions: bool = False
    allow_dictionary: bool = True
    allow_json_report: bool = True
    description: str = ""
    features: tuple[str, ...] = field(default_factory=tuple)

    def permits_candidates(self, count: int) -> bool:
        return self.max_candidates is None or count <= self.max_candidates

    def permits_threads(self, threads: int) -> bool:
        return self.max_threads is None or threads <= self.max_threads


TIERS: dict[str, Tier] = {
    "free": Tier(
        name="free",
        label="Free",
        max_candidates=1_000_000,
        max_threads=1,
        allow_sessions=False,
        description=(
            "Every recovery mode, single core, up to 1,000,000 candidates per run. "
            "Enough for typical one and two character recoveries and small dictionaries."
        ),
        features=("all recovery modes", "1,000,000 candidates per run", "single core"),
    ),
    "trial": Tier(
        name="trial",
        label="Trial",
        max_candidates=None,
        max_threads=None,
        allow_sessions=True,
        description="Full Pro feature set for a limited time.",
        features=("all recovery modes", "unlimited candidates", "all cores", "resume sessions"),
    ),
    "pro": Tier(
        name="pro",
        label="Pro",
        max_candidates=None,
        max_threads=None,
        allow_sessions=True,
        description="Unlimited candidates, every core, resumable sessions and JSON reports.",
        features=(
            "all recovery modes",
            "unlimited candidates",
            "all cores",
            "resume sessions",
            "JSON reports",
            "priority support",
        ),
    ),
    "team": Tier(
        name="team",
        label="Team",
        max_candidates=None,
        max_threads=None,
        allow_sessions=True,
        description="Pro features for a team, licensed per seat, with commercial support.",
        features=("Pro features", "per seat licensing", "commercial support", "invoice billing"),
    ),
}


def get_tier(name: str) -> Tier:
    return TIERS.get((name or "free").lower(), TIERS["free"])
